# CLASSES

class Controller:
    def __init__(self): ...
    def frame(self, history: int = 0) -> Frame: ...

class Finger:
	def direction(self) -> Vector: ...
	def tip_position(self) -> Vector: ...
	def type(self) -> EFingerType: ...

class FingerList:
	def __getitem__(self, idx: int) -> Finger: ...
	def __len__(self) -> int: ...

class Frame:
	def hands(self) -> HandList: ...
	def is_valid(self) -> bool: ...

class Hand:
	def fingers(self) -> FingerList: ...

class HandList:
	def __getitem__(self, idx: int) -> Hand: ...
	def __len__(self) -> int: ...

class Vector:
	x: float
	y: float
	z: float

	def __repr__(self) -> str: ...

# ENUMERATIONS

class EFingerType(int):
	pass

FT_THUMB: EFingerType
FT_INDEX: EFingerType
FT_MIDDLE: EFingerType
FT_RING: EFingerType
FT_PINKY: EFingerType
