# CLASSES

class Bone:
    def next_joint(self) -> Vector: ...
    def prev_joint(self) -> Vector: ...
    def type(self) -> EBoneType: ...
    def width(self) -> float: ...

class Controller:
    def __init__(self): ...
    def enable_gesture(self, gesture_type: EGestureType, enable: bool = True) -> None: ...
    def frame(self, history: int = 0) -> Frame: ...
    def is_gesture_enabled(self, gesture_type: EGestureType) -> bool: ...
    def set_policy(self, policy: EPolicyFlag) -> None: ...

class Finger:
    def bone(self, bone_type: EBoneType) -> Bone: ...
    def direction(self) -> Vector: ...
    def id(self) -> int: ...
    def tip_position(self) -> Vector: ...
    def type(self) -> EFingerType: ...

class FingerList:
    def __getitem__(self, idx: int) -> Finger: ...
    def __len__(self) -> int: ...
    def leftmost(self) -> Finger: ...
    def rightmost(self) -> Finger: ...

class Frame:
    def gestures(self) -> GestureList: ...
    def hands(self) -> HandList: ...
    def is_valid(self) -> bool: ...

class Gesture:
    def duration(self) -> int: ...
    def hands(self) -> HandList: ...
    def id(self) -> int: ...
    def is_valid(self) -> bool: ...
    def state(self) -> EGestureState: ...
    def to_string(self) -> str: ...
    def type(self) -> EGestureType: ...

class GestureList:
    def __getitem__(self, idx: int) -> Gesture: ...
    def __len__(self) -> int: ...

class Hand:
    def fingers(self) -> FingerList: ...
    def is_left(self) -> bool: ...
    def is_right(self) -> bool: ...
    def palm_position(self) -> Vector: ...

class HandList:
    def __getitem__(self, idx: int) -> Hand: ...
    def __len__(self) -> int: ...

class Vector:
    x: float
    y: float
    z: float

    def __repr__(self) -> str: ...

# GESTURE SUBCLASSES

class CircleGesture(Gesture):
    def __init__(self, gesture: Gesture): ...
    def centre(self) -> Vector: ...
    def normal(self) -> Vector: ...
    def progress(self) -> float: ...
    def radius(self) -> float: ...

class KeyTapGesture(Gesture):
    def __init__(self, gesture: Gesture): ...
    def direction(self) -> Vector: ...
    def position(self) -> Vector: ...

class ScreenTapGesture(Gesture):
    def __init__(self, gesture: Gesture): ...
    def direction(self) -> Vector: ...
    def position(self) -> Vector: ...

class SwipeGesture(Gesture):
    def __init__(self, gesture: Gesture): ...
    def direction(self) -> Vector: ...
    def position(self) -> Vector: ...
    def speed(self) -> float: ...
    def start_position(self) -> Vector: ...

# ENUMERATIONS

class EBoneType(int):
    pass

BT_METACARPAL: EBoneType
BT_PROXIMAL: EBoneType
BT_INTERMEDIATE: EBoneType
BT_DISTAL: EBoneType

class EFingerType(int):
    pass

FT_THUMB: EFingerType
FT_INDEX: EFingerType
FT_MIDDLE: EFingerType
FT_RING: EFingerType
FT_PINKY: EFingerType

class EGestureState(int):
    pass

GS_INVALID: EGestureState
GS_START: EGestureState
GS_UPDATE: EGestureState
GS_STOP: EGestureState

class EGestureType(int):
    pass

GT_INVALID: EGestureType
GT_SWIPE: EGestureType
GT_CIRCLE: EGestureType
GT_SCREEN_TAP: EGestureType
GT_KEY_TAP: EGestureType

class EPolicyFlag(int):
    pass

POLICY_DEFAULT: EPolicyFlag
POLICY_BACKGROUND_FRAMES: EPolicyFlag
POLICY_IMAGES: EPolicyFlag
POLICY_OPTIMIZE_HMD: EPolicyFlag
POLICY_ALLOW_PAUSE_RESUME: EPolicyFlag
POLICY_RAW_IMAGES: EPolicyFlag
