#################
# UseLeap.cmake #
#################

FIND_PATH(LEAP_ROOT head_sha.txt HINTS "$ENV{SMGLIB_LEAP_ROOT_DIR}")

IF(WIN32)
  FIND_LIBRARY(LEAP_LIBRARY Leap HINTS "${LEAP_ROOT}/lib/x64")
ELSEIF(APPLE)
  FIND_LIBRARY(LEAP_LIBRARY Leap HINTS "${LEAP_ROOT}/lib")
ELSEIF("${CMAKE_SYSTEM}" MATCHES "Linux")
  FIND_LIBRARY(LEAP_LIBRARY Leap HINTS "${LEAP_ROOT}/lib/x64")
ENDIF()

FIND_PATH(LEAP_INCLUDE_DIR Leap.h HINTS "${LEAP_ROOT}/include")

INCLUDE_DIRECTORIES(${LEAP_INCLUDE_DIR})
